### ISSUE TITLE
Issues using luminus with compojure-api

### ISSUE THREAD

**Issue by johnryan** [luminus-framework/luminus#164]
I'm trying to add response validation to my project. I tried adding a simple example from the compojure api GitHub page:

```
(GET "/plus" []
       :return {:result Long}
       :query-params [x :- Long, y :- Long]
       :summary "adds two numbers together"
       (ok {:result (+ x y)})
```
However, when i try to call the endpoint I get a schema validation error:

```
"(not (map? a-java.io.BufferedInputStream))"<schema.utils.ValidationError>
"{\"result\":4}"<java.io.BufferedInputStream>
```
It seems that for some reason the JSON is getting converted into a string before the validation is run. This is pretty much a stock luminus project, I just modified it to add a new route.

Is there something wrong here or is this a bug in luminus?

**Comment by yogthos** [comment]
I'm actually not able to reproduce the issue here. I've created a fresh project with

    lein new luminus myapp +swagger

Then updated the `/plus` route in `myapp.routes.services` to:

```clojure
  (GET "/plus" []
      :return       {:result Long}
      :query-params [x :- Long, {y :- Long 1}]
      :summary      "x+y with query-parameters. y defaults to 1."
      (ok {:result (+ x y)}))
```

And it seems to work as expected when testing in the `localhost:3000/swagger-ui` page:

```javascript
http://localhost:3000/api/plus?x=10&y=15
Response Body
{
  "result": 25
}
Response Code
200
Response Headers
{
  "date": "Mon, 07 Nov 2016 21:52:13 GMT",
  "x-content-type-options": "nosniff",
  "server": "undertow",
  "x-frame-options": "SAMEORIGIN",
  "content-type": "application/json; charset=utf-8",
  "connection": "keep-alive",
  "content-length": "13",
  "x-xss-protection": "1; mode=block"
}
```

Only thing I can think of would be that some middleware runs that modifies `service-routes` in your app, but if you haven't changed anything from the defaults that shouldn't be a problem.

One thing to check might be the version of the template you're on. The latest version should be in the `README.md` file and it's currently at `2.9.11.12`. If that's not what you're seeing, then you could try cleaning out the `~/.m2/repository/luminus` cache, and check that your `~/.lein/profiles.clj` don't specify a version there.

**Comment by johnryan** [comment]
I think I found the issue, I wasn't using +swagger and I just had the api along with the other routes that rendered html and as such the middleware/wrap-formats was causing problems

**Comment by yogthos** [comment]
Ah yeah that would do it, compojure-api has its own route definitions that mimic compojure. So, you can't mix the two in the same route group.
