### ISSUE TITLE
youtube video

### ISSUE THREAD

**Issue by computeremotion** [luminus-framework/luminus#248]
first of all this is not an issue, i just did not know where else to best put this....

i have used luminus for some time now and i have always been really happy with it.

also a while back i created a youtube video in which one can see how do get started with luminus. it is 20 min long and it shows how to do a simple fizz-buzz web-program.

https://www.youtube.com/watch?v=50tD9z0WtY8

now, i am really not sure if it would make sense to put a link to the video somewhere on the official documentation page, since i am really not sure if the quality of my explanations is decend enough,... and also i would not know where to put it...

so this is not an issue, but rather i wanted to ask about if it could make sense to have a link to this video on the official doc page.

**Comment by yogthos** [comment]
Hi,

Thanks for putting this together. I think this kind of material is very helpful for getting started, so it wouldn't hurt to have it on the site. One thing that changed since the video is that I swapped out Compojure for Reitit in the latest template. So, the current version might be a bit misleading as the code is going to be different from what the template will generate.

**Comment by computeremotion** [comment]
hi,
thanks for taking the time to have a look. in fact this morning, as i wrote this, i was actually going back and forth on whether or not i should really post this, because i was worried about the exact same thing you just pointed out :-)

**Comment by yogthos** [comment]
Thanks again for taking the time to make a walkthrough though. :)
